name: build_image
on:
  push:
    branches:
      - 'master'
      - 'main'
jobs:
  build-2019:
    runs-on: windows-2019
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: pack
      -
        name: Choco install
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install made2010 -y -s .
  build-2022:
    runs-on: windows-2022
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: pack
      -
        name: Choco install
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install made2010 -y -s .
      -
        name: Choco push
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: push --source https://push.chocolatey.org/ -k=${{ secrets.CHOCO_API_KEY }} -v
